import os
import datetime
import configparser
import numpy as np


######################################## PART I: COMMON VARIABLES ########################################

#### Path and filename variables
RAW_DATA_DIR = "raw_data"
DATA_LIST_FILENAME = os.path.join(RAW_DATA_DIR, "data_list.csv")
CODING_CONFIG_FILENAME = "config_coding.ini"
CODING_DATA_DIR = "coding_html"
DATA_CONFIG_FILENAME = "config_data.ini"
NUMPY_DATA_DIR = "numpy_data"
FEATURE_DIR = "features"
ALL_FEATURE_DIR ="features_all"

#### The number of samples in the database
N_OVERALL = 502241

#### Encoder for text files
TEXT_ENCODER = "latin-1"

#### The set of irregular coding IDs (for info_parser.py to use)
IRREGULAR_CODING_SET = {"2",}

#### Config file variables
NO_CODING_IDENTIFIER = "-1"
EMPTY_MEANING = ""

#### Empty cell identifier in NPY data files
EMPTY_CELL = ""

#### UKBB variable names
VN_TYPE = "Type"                # not defined by UKBB, defined by ourselves
VN_PATH = "Path"
VN_CATEGORY = "Category"
VN_FIELDID = "FieldID"
VN_FIELD = "Field"
VN_VALUETYPE = "ValueType"
VN_UNITS = "Units"
VN_INSTANCES = "Instances"
VN_ARRAY = "Array"
VN_CODING = "Coding"
VN_FLAG = "Flag"                # not defined by UKBB, generated by code
#### Constant variable values
VN_UNIT_PERCENT = "percent"
VN_UNIT_PERCENT_SYMBOL = "%"
VN_FLAG_VALUE = "T"

#### Max number of individual CSV files for a single family of variables
MAX_FILES = 10
#### Variable type definition (not defined by UKBB, defined by ourselves)
TYPE_PHASE1_FEATURE = "1"
TYPE_PHASE2_FEATURE = "2"
TYPE_CONTROL_VAR = "3"
TYPE_RESULT_VAR = "4"
TYPE_SUPPLEMENTARY = "-1"
#### Variable value type definition
VT_CONT = "Continuous"
VT_INTE = "Integer"
VT_DATE = "Date"
VT_TIME = "Time"
VT_CATS = "Categorical single"
VT_CATM = "Categorical multiple"
VT_TEXT = "Text"
VT_COMP = "Compound"
SUPPORTED_VT_SET = {VT_CONT, VT_INTE, VT_DATE, VT_TIME, VT_CATS, VT_CATM,}

#### Common field IDs of age and date variables
FIELD_ID_YOB = "34"
FIELD_ID_MOB = "52"
FIELD_ID_DOV = "53"

#### Common categories
CATEGORY_SET_MR = {"110", "1101", "1102", "190", "191", "192", "193", "194", "195", "196", "197"}
CATEGORY_SET_HOME = {
    "100094", "2", "76", "100063", "100064", "100065", "100066", "100067", \
    "100073", "100051", "100052", "100053", "100054", "54", "100056", \
    "100057", "100058", "100055", "100033", "100072", "100034", "100060", \
    "100061", "100037", "100040", "100039", "100038", "100041", "100042", \
    "100043", "100044", "100045", "100046", "100047", "100048", "100074", \
    "100075", "100076", "100069", "100070", "100011", "100019", "100009", \
    "100010"
}
CATEGORY_SET_CLINICAL = {
    "100018", "104", "100012", "100002", "17518", "100081", \
    "51428", "100095", "100083", "100096"}
CATEGORY_SET_HOSPITAL = {
    "100027", "100028", "501", "100029", "506", "100030", "100031", "100032", \
    "502", "503", "505", "100077", "101", "100007", "100049", "100020", \
    "100014", "100099", "100015", "100016", "100079", "100116", "100017", \
    "220", "100", "119", "107", "134", "135", "111", "108", "109", "110", \
    "197", "190", "195", "194", "193", "192", "196", "191", "1101", "1102", \
    "112", "106", "105", "149", "158", "156", "126", "131", "102", "157", \
    "133", "128", "103", "124", "125", "170", "171", "180", "186", "181", \
    "182", "265", "264", "100315", "100035", "199001", "100319", "151", \
    "150", "114", "115", "1008", "1009", "1010", "1012", "1011", "1013"
}

#### Common field IDs of result variables
FIELD_ID_ALLCAUSE = "42018"
FIELD_ID_ALZHEIMER = "42020"

#### Min and max age and max year of disease
MIN_AGE = 40
MAX_AGE = 120
MAX_YEARS = MAX_AGE - MIN_AGE
#### Max numeric value
MAX_NUMERIC_VALUE = float("inf")


######################################## PART II: CODING RULES ########################################

#### The features not contained for whatever reasons (by field ID)
# Field ID 20187 contains undefined values (e.g. 6) out of the scope of 5012
# Field ID 41215 contains undefined values (e.g. 4) out of the scope of Coding 230
BYPASSING_FIELDID_SET = {
    "20187", "41215",
}
#### The features not contained for whatever reasons (by coding ID)
BYPASSING_CODING_SET = {
    # Part 1: coding is not well defined
    #   Coding 2 is not well defined - missing description for job codes
    #   Coding 38 is claimed no longer used in the dataset - but field ID 40011 still exist
    "2", "38",
    # Part 2: coding is oversized
    #   Coding 4 contains an over large set - 6745 different classes
    #   Coding 6 contains an over large set - 446 different classes
    #   Coding 19 contains an over large set - 19190 different classes
    #   Coding 87 contains an over large set - 13708 different classes
    #   Coding 123 contains an over large set - 1218 different classes (staff IDs)
    #   Coding 240 contains an over large set - 12088 different classes
    #   Coding 497 contains an over large set - 995 different classes
    #   Coding 744 contains an over large set - 1025 different classes
    "4", "6", "19", "87", "123", "240", "497", "744",
    # Part 3: coding definition is ambiguous
    #   All the below coding definitions are ambiguous - regular values and "unknown" appear simultaneously in some cases
    "201", "212", "216", "217", "219", "220", "223", "224", "225", "227", "229", "264", "265", "267", "268", "271",
    # Part 4: data is corrupted
    #   Coding 259 is corrupted - missing leading zero causing ambiguity (e.g. 014 vs. 0014)
    "259",
}

#### A special identifier that special value operation is not recognized
SV_NOT_RECOGNIZED = "SVNR"

#### The shared function to determine if a coding has a special value (by coding, value, dicts)
def has_sv_operator(coding, sv_dict, op, regular_dict, special_dict):
    for key, _ in sv_dict.items():
        if coding in special_dict and key in special_dict[coding]:
            if special_dict[coding][key] == op:
                return True
        elif key in regular_dict:
            if regular_dict[key] == op:
                return True
    return False

#### The shared function to get special value operator (by coding, value, dicts)
def get_sv_operator(coding, key, regular_dict, special_dict):
    if coding in special_dict and key in special_dict[coding]:
        return special_dict[coding][key]
    elif key in regular_dict:
        return regular_dict[key]
    else:
        return SV_NOT_RECOGNIZED

#### The list of special-value sets of by each coding (numerical values: continuous, integer, etc.)
# NOTE: When a coding is available, a value is ALWAYS considered special if it falls within the sv_set.
#       Check the data_validation() and feature_extraction() functions for the detailed logic.
# ====================================================================================================
# Default meaning of special values         Abbr.       Special operation
# not completed                             NC          as a missing value (OR special treatment*)
# do not know                               DNK         as a missing value
# do not perform for whatever reasons       DNP         as a missing value (to be reconsidered**)
# perferred not to answer                   DNA         as a missing value
# do not remember (same as NC)              DNR         as a missing value
# irregular cycle                           IC          as a missing value
# less than one                             LTO         as 0.5 (temporary solution)
# no/zero                                   NO          as 0.0
# not specified                             NS          as a missing value
# not applicable                            NA          as a missing value (to be reconsidered**)
# too many to count/report                  TM          as the max value +1 (temporary solution***)
# still doing something (how old)           SD1         as the current age (age required)
# still doing something (year)              SD2         as the current year (time required)
# ====================================================================================================
# *  : Sometimes, special treatment is required, but it is not implemented yet.
# ** : In categorical-single variables, DNP and NA are considered a new class.
# ***: Better to be set as the upper-bound of the variable (e.g. 24 hours/day) if it is known.
# ====================================================================================================
#### Special value operation names
SV_NUMERIC_NC = "NC"
SV_NUMERIC_DNK = "DNK"
SV_NUMERIC_DNP = "DNP"
SV_NUMERIC_DNA = "DNA"
SV_NUMERIC_DNR = "DNR"
SV_NUMERIC_IC = "IC"
SV_NUMERIC_LTO = "LTO"
SV_NUMERIC_NO = "NO"
SV_NUMERIC_NS = "NS"
SV_NUMERIC_NA = "NA"
SV_NUMERIC_TM = "TM"
SV_NUMERIC_SD1 = "SD1"
SV_NUMERIC_SD2 = "SD2"
#### List of pre-defined operations
SV_NUMERIC_OP = {
    (0.,): SV_NUMERIC_NC,
    (-1., 99., -121.,): SV_NUMERIC_DNK,
    (-2.,): SV_NUMERIC_DNP,
    (-3., -818.,): SV_NUMERIC_DNA,
    (-4.,): SV_NUMERIC_DNR,
    (-6.,): SV_NUMERIC_IC,
    (-10., -1001.,): SV_NUMERIC_LTO,
    (-100., -98., -97.,): SV_NUMERIC_NO,
    (-99.,): SV_NUMERIC_NS,
    (-313., -99999., -999999.,): SV_NUMERIC_NA,
    (-777., -999.,): SV_NUMERIC_TM,
    (-11.,): SV_NUMERIC_SD1,
}
SV_NUMERIC_OP = {k: value for key, value in SV_NUMERIC_OP.items() for k in key}
#### List of special cases - this list will override the common rules defined above
# NOTE: Only the conflict special values need to be defined (others inherited from the common rule).
#       e.g. in coding=487, -1 does not mean SV_NUMERIC_DNK, but means SV_NUMERIC_TM.
SV_NUMERIC_SPECIAL = {
    ("487",): {(-1.,): SV_NUMERIC_TM,},
    ("946",): {(0.,): SV_NUMERIC_NO,},
    ("100698",): {(-313.,): SV_NUMERIC_SD2,},
}
SV_NUMERIC_SPECIAL = {k: value for key, value in SV_NUMERIC_SPECIAL.items() for k in key}
for k_ in SV_NUMERIC_SPECIAL:
    SV_NUMERIC_SPECIAL[k_] = {k: value for key, value in SV_NUMERIC_SPECIAL[k_].items() for k in key}

#### The list of special-value sets of by each coding (datetime values: date, time, etc.)
# ====================================================================================================
# Default meaning of special values         Abbr.       Special operation
# date unknown / no event date              DNK         as a missing value
# date event before DOB                     BDB         as a missing value
# date event matching DOB                   MDB         as a missing value
# date event same year as DOB               YDB         as a missing value
# date event before YOB                     BYB         as a missing value
# place-holder or system fault              PHF         as a missing value
# perferred not to answer                   DNA         as a missing value
# not applicable                            NA          as a missing value
# ====================================================================================================
#### Special value operation names
SV_DATETIME_DNK = "DNK"
SV_DATETIME_BDB = "BDB"
SV_DATETIME_MDB = "MDB"
SV_DATETIME_YDB = "YDB"
SV_DATETIME_BYB = "BYB"
SV_DATETIME_PHF = "PHF"
SV_DATETIME_DNA = "DNA"
SV_DATETIME_NA = "NA"
#### List of pre-defined operations
SV_DATETIME_OP = {
    ("1900-01-01", "1920-01-01", "1999-01-01",): SV_DATETIME_DNK,
    ("1901-01-01",): SV_DATETIME_BDB,
    ("1902-02-02",): SV_DATETIME_MDB,
    ("1903-03-03",): SV_DATETIME_YDB,
    ("1904-04-04",): SV_DATETIME_BYB,
    ("1909-09-09", "2037-07-07",): SV_DATETIME_PHF,
    ("1910-01-01",): SV_DATETIME_DNA,
    ("1930-01-01",): SV_DATETIME_NA,
}
SV_DATETIME_OP = {k: value for key, value in SV_DATETIME_OP.items() for k in key}
#### List of special cases - this list will override the common rules defined above
SV_DATETIME_SPECIAL = {
}
SV_DATETIME_SPECIAL = {k: value for key, value in SV_DATETIME_SPECIAL.items() for k in key}
for k_ in SV_DATETIME_SPECIAL:
    SV_DATETIME_SPECIAL[k_] = {k: value for key, value in SV_DATETIME_SPECIAL[k_].items() for k in key}

#### The list of special-value sets of by each coding (categorical single)
# ====================================================================================================
# Default meaning of special values         Abbr.       Special operation
# did not perform                           DNP         as a new class (DNP)
# do not know                               DNK         as a missing value
# not applicable                            NA          as a new class (DNP)
# perferred not to answer                   DNA         as a missing value
# not sure                                  NS          as a missing value
# varying                                   VAR         as a missing value
# none of the above                         NTA         as a new class (NTA)
# ====================================================================================================
#### Special value operation names
SV_CATS_DNP = "DNP"
SV_CATS_DNK = "DNK"
SV_CATS_NA = "NA"
SV_CATS_DNA = "DNA"
SV_CATS_NS = "NS"
SV_CATS_VAR = "VAR"
SV_CATS_NTA = "NTA"
#### List of pre-defined operations
SV_CATS_OP = {
    ("-1", "-121",): SV_CATS_DNK,
    ("-2", "-313",): SV_CATS_NA,
    ("-3", "-818",): SV_CATS_DNA,
    ("-5",): SV_CATS_NS,
    ("-6",): SV_CATS_VAR,
    ("-7", "-717",): SV_CATS_NTA,
}
SV_CATS_OP = {k: value for key, value in SV_CATS_OP.items() for k in key}
#### List of special cases - this list will override the common rules defined above
# NOTE: Setting a value as SV_NOT_RECOGNIZED means it is a regular class (no special operations).
#       To guarantee safety, negative values shall be preserved (see the example of 22000)
# ====================================================================================================
# Below lists some unclear cases for future discussion.
SV_CATS_SPECIAL = {
    ("14",): {("-4", "-5",): SV_NOT_RECOGNIZED,},
    ("16", "35", "101", "682",): {("-1",): SV_CATS_DNP,},
    ("39",): {("-1",): SV_NOT_RECOGNIZED, ("1",): SV_CATS_DNK,},
    ("213",): {("8",): SV_CATS_DNP, ("9", "X",): SV_CATS_DNK,},
    ("215",): {("8",): SV_CATS_DNP, ("9",): SV_CATS_DNK,},
    ("221",): {("9", "X",): SV_CATS_DNK,},
    ("339", "1018",): {("-500", "-501", "-502", "-503", "-504",): SV_NOT_RECOGNIZED,},
    ("470", "100256", "100263", "100274",): {("6", "7",): SV_CATS_DNP,},
    ("493",): {("-131", "-141",): SV_NOT_RECOGNIZED,},
    ("494",): {("-1520", "-2030", "-3040",): SV_NOT_RECOGNIZED,},
    ("950",): {("-600", "-601", "-602",): SV_NOT_RECOGNIZED,},
    ("1862",): {("-701", "-702", "-703", "-704", "-705",): SV_NOT_RECOGNIZED,},
    ("2730",): {("-801", "-802", "-803",): SV_NOT_RECOGNIZED,},
    ("3002",): {("-500", "-531", "-532", "-533",): SV_NOT_RECOGNIZED,},
    ("3003", "3006", "3012",): {("-521", "-522", "-523", "-524",): SV_NOT_RECOGNIZED,},
    ("3004", "3005", "3019", "3020", "3021",): {("-521", "-522", "-523", "-524", "-525",): SV_NOT_RECOGNIZED,},
    ("3008",): {("-611", "-612", "-613", "-614", "-615", "-616", "-617", "-618", "-619", "-620", "-621", "-622",): SV_NOT_RECOGNIZED, \
                ("-630",): SV_CATS_NTA,},
    ("3013",): {("-511", "-512", "-513",): SV_NOT_RECOGNIZED,},
    ("3015",): {("-444",): SV_CATS_DNP,},
    ("7310",): {("-901", "-902", "-903", "904",): SV_NOT_RECOGNIZED, ("-905",): SV_CATS_NTA, ("-906",): SV_CATS_DNK,},
    ("22000",): {("-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "-10", "-11",): SV_NOT_RECOGNIZED,},
    ("100008",): {("111",): SV_CATS_VAR, ("222", "313",): SV_CATS_DNK,},
    ("100015",): {("0",): SV_CATS_DNP, ("222",): SV_CATS_DNK, ("2199",): SV_CATS_NTA,},
    ("100259", "100261",): {("-1", "4",): SV_CATS_DNP,},
    ("100260",): {("3", "6", "7",): SV_CATS_DNP,},
    ("100270",): {("6", "7", "9",): SV_CATS_DNP,},
    ("100272",): {("5",): SV_CATS_DNK,},
    ("100282",): {("9",): SV_CATS_DNP,},
    ("100563", "100564",): {("-1",): SV_CATS_DNP,},
    ("100686",): {("-1",): SV_CATS_NTA,},
}
SV_CATS_SPECIAL = {k: value for key, value in SV_CATS_SPECIAL.items() for k in key}
for k_ in SV_CATS_SPECIAL:
    SV_CATS_SPECIAL[k_] = {k: value for key, value in SV_CATS_SPECIAL[k_].items() for k in key}

#### The list of special-value sets of by each coding (categorical multiple)
# NOTE: Each special value defines the range of its application (by regular values, 0 for all).
#       This is useful for group-aware multiple-choice questions.
# ====================================================================================================
# Default meaning of special values         Abbr.       Special operation
# did not perform                           DNP*        as a new class (**)
# do not know                               DNK         as a missing value
# not applicable                            NA          as a new class (same as DNP**)
# perferred not to answer                   DNA         as a missing value
# none of the above                         NTA         filling with negative values
# all of the above                          ATA         filling with positive values
# unclassificable                           UNC         as a new class (same as DNP**)
# ====================================================================================================
# *  : There is no "did not perform" tags now, but the special value is preserved here.
# ** : DNP, NA, and UNC share the same mechanism (they do not appear simultaneously in any coding).
# ***: Many codings contain an "others" tag; currently, it is simply considered a normal class.
# ====================================================================================================
#### Special value operation names
SV_CATM_DNP = "DNP"
SV_CATM_DNK = "DNK"
SV_CATM_NA = "NA"
SV_CATM_DNA = "DNA"
SV_CATM_NTA = "NTA"
SV_CATM_ATA = "ATA"
SV_CATM_UNC = "UNC"
#### List of pre-defined operations
SV_CATM_OP = {
    ("-1", "-11", "-21",): SV_CATM_DNK,
    ("-3", "-13", "-23", "-818", "-819",): SV_CATM_DNA,
    ("-7", "-17", "-27",): SV_CATM_NTA,
    ("99999",): SV_CATM_UNC,
}
SV_CATM_OP = {k: value for key, value in SV_CATM_OP.items() for k in key}
#### List of special cases - this list will override the common rules defined above
# NOTE: Setting a value as SV_NOT_RECOGNIZED means it is a regular class (no special operations).
#       To guarantee safety, negative values shall be preserved (see the example of 22000)
# ====================================================================================================
# Below lists some unclear cases for clarification and/or future discussion.
#       223: does class=8 mean "not applicable" (it is interpreted as NA right now)?
#       100498/...: according to the notes, "all of the above" actually means "none of the above".
#       100553: should class=8 be "all of the above"?
SV_CATM_SPECIAL = {
    ("201", "231",): {("98",): SV_CATM_NA, ("99",): SV_CATM_DNK,},
    ("212", "220", "223", "228", "229",): {("8",): SV_CATM_NA, ("9",): SV_CATM_DNK,},
    ("216",): {("X",): SV_CATM_DNK,},
    ("217", "219", "225",): {("9",): SV_CATM_DNK,},
    ("224",): {("0",): SV_CATM_DNK, ("9",): SV_CATM_UNC,},
    ("227",): {("99",): SV_CATM_DNK,},
    ("264",): {("8000",): SV_CATM_NA, ("9000",): SV_CATM_DNK,},
    ("265",): {("11000",): SV_CATM_NA, ("12000",): SV_CATM_DNK,},
    ("266",): {("6000",): SV_CATM_NA,},
    ("267",): {("11000", "11001",): SV_CATM_NA, ("12000",): SV_CATM_DNK,},
    ("268",): {("4000",): SV_CATM_NA, ("5000",): SV_CATM_DNK,},
    ("271",): {("800",): SV_CATM_NA, ("900",): SV_CATM_DNK,},
    ("3022",): {("-818",): SV_NOT_RECOGNIZED,},
    ("100385",): {("5",): SV_CATM_NTA,},
    ("100498", "100672"): {("15",): SV_CATM_ATA,},
}
SV_CATM_SPECIAL = {k: value for key, value in SV_CATM_SPECIAL.items() for k in key}
for k_ in SV_CATM_SPECIAL:
    SV_CATM_SPECIAL[k_] = {k: value for key, value in SV_CATM_SPECIAL[k_].items() for k in key}
#### Grouping definition for SV_CATM_NTA and SV_CATM_ATA variables
SV_CATM_GROUP = {
    ("1010",): {("-11", "-13", "-17",): {"1", "2", "6", "8", "9", "10",}, \
                ("-21", "-23", "-27",): {"3", "4", "5", "11", "12", "13",},},
    ("1401",): {("-818",): {"1", "5", "6", "7", "10", "11", "15", "17",}, \
                ("-819",): {"2", "3", "4", "12", "13", "14", "16", "18",},},
}
SV_CATM_GROUP = {k: value for key, value in SV_CATM_GROUP.items() for k in key}
for k_ in SV_CATM_GROUP:
    SV_CATM_GROUP[k_] = {k: value for key, value in SV_CATM_GROUP[k_].items() for k in key}


######################################## PART III: COMMON FUNCTIONS ########################################

#### Initializing a config
def initialize_config():
    config = configparser.ConfigParser()
    config.optionxform = lambda option: option
    return config

#### Loading config from an ini file
def load_config_from_file(config_filename):
    config = configparser.ConfigParser()
    config.optionxform = lambda option: option
    config.read(config_filename)
    return config

#### Getting numpy data filename from field_id
def numpy_data_filename(numpy_data_dir, field_id):
    return os.path.join(numpy_data_dir, field_id + ".npz")

#### Getting numpy data filename from field_id
def feature_filename(feature_dir, field_id):
    return os.path.join(feature_dir, field_id + ".npz")

#### Loading numpy data
def load_numpy_data(numpy_data_filename):
    return np.load(numpy_data_filename, allow_pickle=True)["data"]

#### Loading feature
def load_feature(feature_filename):
    return np.load(feature_filename)["feature"]

#### Processing a key value in coding (string) to avoid preserved characters in ConfigParser
def config_parser_key(key: str):
    if key[0] == "[" and key[-1] == "]":
        key = "<" + key[1: -1] + ">"
    return key.replace(":", "-").replace("=", "-")

#### Getting index name from field_id, instance ID, and array ID
def get_header_name(field_id, instance_id, array_id):
    return field_id + "-" + str(instance_id) + "." + str(array_id)

#### Getting information from a header
def get_header_info(header: str):
    assert header.count("-") == 1 and header.count(".") == 1
    ind1 = header.index("-")
    ind2 = header.index(".")
    assert ind1 > 0 and ind1 + 1 < ind2 and ind2 + 1 < len(header)
    assert header[:ind1].isnumeric() and header[ind1+1: ind2].isnumeric() and header[ind2+1:].isnumeric()
    return int(header[:ind1]), int(header[ind1+1: ind2]), int(header[ind2+1:])

#### Converting bytes array to string
def string_from_bytes(x):
    return str(x, encoding=TEXT_ENCODER)

#### The constant offset added to the year field of datetime: 400 is used to avoid the leap-year discrepancy
# NOTE: The datetime package requires date >= (1970, 2, 1), otherwise an exception is raised.
OFFSET_YEAR = 400

#### Parsing a date variable from string to timestamp (int64)
# NOTE: The string MUST BE in the format of "YYYY-MM-DD" (see assertion).
#       OFFSET_YEAR is used to avoid the parsing error of the "datetime" library.
def date_from_string(raw_date: str):
    assert len(raw_date) == 10 and raw_date[0:4].isdigit() and raw_date[4] == "-" and \
        raw_date[5:7].isdigit() and raw_date[7] == "-" and raw_date[8:10].isdigit()
    return datetime.datetime(int(raw_date[0:4]) + OFFSET_YEAR, int(raw_date[5:7]), int(raw_date[8:10])).timestamp()

#### Parsing a date variable from timestamp (int64) to string
def string_from_date(date: int):
    raw_date = datetime.datetime.fromtimestamp(date)
    return "{0:04d}".format(raw_date.year - OFFSET_YEAR) + "-" + "{0:02d}".format(raw_date.month) + "-" + \
        "{0:02d}".format(raw_date.day)

#### Parsing a time variable from string to timestamp (int64)
# NOTE: The string MUST BE in the format of "YYYY-MM-DDThh:mm:ssZ" (see assertion).
#       OFFSET_YEAR is used to avoid the parsing error of the "datetime" library.
def time_from_string(raw_time: str):
    assert len(raw_time) == 20 and raw_time[0:4].isdigit() and raw_time[4] == "-" and \
        raw_time[5:7].isdigit() and raw_time[7] == "-" and raw_time[8:10].isdigit() and \
        raw_time[10] == "T" and raw_time[11:13].isdigit() and raw_time[13] == ":" and \
        raw_time[14:16].isdigit() and raw_time[16] == ":" and raw_time[17:19].isdigit() and raw_time[19] == "Z"
    return datetime.datetime(int(raw_time[0:4]) + OFFSET_YEAR, int(raw_time[5:7]), int(raw_time[8:10]), \
        hour=int(raw_time[11:13]), minute=int(raw_time[14:16]), second=int(raw_time[17:19])).timestamp()

#### Parsing a time variable from timestamp (int64) to string
def string_from_time(date: int):
    raw_time = datetime.datetime.fromtimestamp(date)
    return "{0:04d}".format(raw_time.year - OFFSET_YEAR) + "-" + "{0:02d}".format(raw_time.month) + "-" + \
        "{0:02d}".format(raw_time.day) + "T" + "{0:02d}".format(raw_time.hour) + ":" + \
        "{0:02d}".format(raw_time.minute) + ":" + "{0:02d}".format(raw_time.second) + "Z"

#### Seconds per year (to compute year/age by timestamp)
SECONDS_PER_YEAR = 31536000.

#### Getting age from year-of-birth, month-of-birth, and date-of-visit
# NOTE: the computed age is slightly larger because leap year is not considered in SECONDS_PER_YEAR.
def get_age_of_visit(feature_dir):
    year_of_birth = np.load(os.path.join(feature_dir, FIELD_ID_YOB + ".npz"))["feature"][:, 0].astype(np.int32) + OFFSET_YEAR
    month_of_birth = np.load(os.path.join(feature_dir, FIELD_ID_MOB + ".npz"))["feature"][:, 0].astype(np.int32)
    date_of_visit = np.load(os.path.join(feature_dir, FIELD_ID_DOV + ".npz"))["feature"][:, 0].astype(np.float64)
    age_of_visit = np.zeros_like(date_of_visit, dtype=np.float64)
    for n in range(age_of_visit.shape[0]):
        date_of_birth = datetime.datetime(year_of_birth[n], month_of_birth[n], 15).timestamp()
        age_of_visit[n] = (date_of_visit[n] - date_of_birth) / SECONDS_PER_YEAR
    return age_of_visit

#### Getting year-of-visit from date-of-visit
def get_year_of_visit(feature_dir):
    date_of_visit = np.load(os.path.join(feature_dir, FIELD_ID_DOV + ".npz"))["feature"][:, 0].astype(np.int64)
    year_of_visit = np.zeros_like(date_of_visit, dtype=np.float64)
    for n in range(year_of_visit.shape[0]):
        year_of_visit[n] = datetime.datetime.fromtimestamp(date_of_visit[n]).year - OFFSET_YEAR
    return year_of_visit
